### PR TITLE
[SYCLomatic #1526] Add tests for 3 partition mappings

### PR DESCRIPTION
**Pull request by mmichel11**
This PR tests the implementation for the following partition APIs implemented in https://github.com/oneapi-src/SYCLomatic/pull/1526. Two tests are written to cover these APIs.

- dpct::partition_flagged
- dpct::partition_if with one output buffer
- dpct::partition_if with three output buffers

### CODE REVIEW

**Comment by mmichel11** [comment]
Tests have been updated to check the optional reverse property on the last partition in the output(s).

**Review by tomflinda — APPROVED** [review]
LGTM

**Comment by jiejanezhang** [comment]
Yihan has open on this PR. Let's hold.

**Comment by mmichel11** [comment]
@yihanwg @jiejanezhang 
I have added a USM test for the three-way `dpct::partition_if` API that uses `std::reverse_iterator` and combines the allocation for the second and third output sequences. This provides coverage over the reported oneDPL bug.

Please note that this will trigger asserts with oneDPL builds prior to the recently merged https://github.com/oneapi-src/oneDPL/pull/1413 patch.

**Review by yihwang-nv — APPROVED** [review]
LGTM

**Review by ShengchenJ — APPROVED** [review]

**Comment by ShengchenJ** [comment]
onedpl_test_partition_if failed on CPU, @mmichel11  Could you help take a look?

**Comment by mmichel11** [comment]
> onedpl_test_partition_if failed on CPU, @mmichel11 Could you help take a look?

Looking at the CI, it looks like oneDPL version from `20240205` is being used. The failing test is the last which contains a usage of `std::reverse_iterator` which has been recently patched in oneDPL. For this test to pass, we need a oneDPL build after [oneDPL #1413](https://github.com/oneapi-src/oneDPL/pull/1413) which I believe has been recently provided.

**Comment by mmichel11** [comment]
`dpct::partition_flagged` and `dpct::partition_if` tests are now passing with updated oneDPL version.

**Comment by ShengchenJ** [comment]
@mmichel11 Merged.

**Pull request merged**
