### PR TITLE
[SYCLomatic-test]update dpl load test

### PR DESCRIPTION
**Pull request by abhilash1910**
Update dpl load test with udpated headers. 
cc @yihanwg @tomflinda @zhimingwang36

### CODE REVIEW

**Review by tomflinda — APPROVED** [review]
LGTM

**Review by yihwang-nv — CHANGES_REQUESTED** [review]
This change was not the correct approach. we only need to include <dpct/group_utils.hpp> . onedpl_test_group_load.cpp is the test for the old load algorithm, but the changes in this PR was switched to test new load algorithm

**Review by tomflinda — CHANGES_REQUESTED** [review]
@abhilash1910 
As this test case only test the help function in clang/runtime/dpct-rt/include/dpct/group_utils.hpp, pls change the test case name from "onedpl_test_group_load.cpp" to "dpct_test_group_load.cpp"

**Review by tomflinda — APPROVED** [review]
LGTM

**Review by yihwang-nv — APPROVED** [review]

**Pull request merged**
