### PR TITLE
Add test for migrating thrust::tuple_element

### PR DESCRIPTION
**Pull request by delecui**

### CODE REVIEW

**Comment by delecui** [comment]
This PR is the test for https://github.com/oneapi-src/SYCLomatic/pull/41

**Comment by delecui** [comment]
This test has been verified with local build. 
it should pass after https://github.com/oneapi-src/SYCLomatic/pull/41 is merged

**Review by tomflinda — APPROVED** [review]
LGTM

**Review by ShengchenJ — APPROVED** [review]
LGTM

**Pull request merged**
