### PR TITLE
[SYCLomatic #481] Enable test for dpct::device_vector move semantics

### PR DESCRIPTION
**Pull request by Nuullll**
Signed-off-by: Yilong Guo <yilong.guo@intel.com>

### CODE REVIEW

**Comment by Nuullll** [comment]
Header fix: https://github.com/oneapi-src/SYCLomatic/pull/481

**Comment by Nuullll** [comment]
https://github.com/oneapi-src/SYCLomatic/pull/481 has been merged. Could anyone help approve running workflows again? Thanks.

**Comment by Nuullll** [comment]
> Error: The action has timed out.

The timeout of windows-test-features-cpu should be irrelevant.

**Comment by Nuullll** [comment]
ping :-)

**Review by zhimingwang36 — APPROVED** [review]
LGTM

**Pull request merged**
