### PR TITLE
[SYCLomatic] Add test case for Libcu atomic

### PR DESCRIPTION
**Pull request by wenhuiNi**

### CODE REVIEW

**Comment by wenhuiNi** [comment]
atomic not merge, waiting for SYClomatic libcu_atomic merge

**Comment by wenhuiNi** [comment]
Microsoft Windows [Version 10.0.17763.2028]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\wenhuini>R:/u4win/u4w_bash.bat

   U4WIN Setup done
   Version 2.0.24 25-Jan-2020

bash-3.2$ export ICS_START=r:/ics/itools/win/bin/
bash-3.2$ source $ICS_START/icssetup.sh
Setting environment supplied defaults: xmain latest xmainefi2win qa_release
ics unset config -ws
ics set config -shws xmain 20220907 xmainefi2win qa_release
bash-3.2$ source $ICS_START/icsenv.sh
bash-3.2$ ics ws -archive deploy_syclct llorgsyclctefi2win $(date -d "1 day ago" +"%Y%m%d")_000000

Selecting Archive/CSB area:
 //shcfsv01a-cifs.sh.intel.com/cmplrarch/deploy_syclct/llorgsyclctefi2win/20220907_000000

Current workspace set to: //shcfsv01a-cifs.sh.intel.com/cmplrarch/deploy_syclct/llorgsyclctefi2win/20220907_000000

Current Focus set to: WS

Current mode set to: deploy frozen

bash-3.2$ ics set config -ws llorgsyclctefi2win qa_release cmplr=xmainrel VS=2022 XMAINCOMPVER=$(date -d "1 day ago" +"%Y%m%d")_160000
setting ICS_UCOPTIONS to XMAINCOMPVER=20220907_160000
warning: root for CUDASAMPLE does not exist: //shcfsv01a-cifs.sh.intel.com/lref1/ref/cuda_samples/win
warning: version for DPSTDCSB is not set
warning: root for DPSTDRELCSB does not exist: //shcfsv01a-cifs.sh.intel.com/cmplrarch/change_sets/deploy_xmain-rel/xmaindpcpplibefi2win
warning: version for XMAINCSBCOMP is not set
warning: version for XMAINRELCSBCOMP is not set
ics set config -ws llorgsyclctefi2win qa_release cmplr=xmainrel VS=2022
bash-3.2$ wcontext
warning: root for CUDASAMPLE does not exist: //shcfsv01a-cifs.sh.intel.com/lref1/ref/cuda_samples/win
warning: version for DPSTDCSB is not set
warning: root for DPSTDRELCSB does not exist: //shcfsv01a-cifs.sh.intel.com/cmplrarch/change_sets/deploy_xmain-rel/xmaindpcpplibefi2win
warning: version for XMAINCSBCOMP is not set
warning: version for XMAINRELCSBCOMP is not set
ics set context WS HOST vs=2022 cmplr=XMAINREL
bash-3.2$ cd d:
bash-3.2$ cd iusers/
bash-3.2$ cd wenhuini/
bash-3.2$ cd workstation/
bash-3.2$ cd SYCLomatic-test/
bash-3.2$ python3 run_test.py --suite help_function --case libcu_atomic --option option_usmnone_gpu
============= libcu_atomic: PASS ==================

========== Device Runtime Info: ===============
Warning: SYCL_DEVICE_FILTER environment variable is set to LEVEL_ZERO:GPU.
To see the correct device id, please unset SYCL_DEVICE_FILTER.

[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) UHD Graphics 630 1.3 [1.3.0]

=============================================

----------------------------
atomic test
Selected device: Intel(R) UHD Graphics 630
Measured time for parallel execution with std::chrono::steady_clock = 392.153 ms
device result: 1 , cpu result: 1
device result: 1 , cpu result: 1
device result: 3 , cpu result: 3
device result: 4 , cpu result: 4
device result: 8 , cpu result: 8
device result: 9 , cpu result: 9
Atomics test completed, returned OK

----------------------

----------------Test pass-----------------
bash-3.2$ python3 run_test.py --suite help_function --case libcu_atomic --option option_gpu
============= libcu_atomic: PASS ==================

========== Device Runtime Info: ===============
Warning: SYCL_DEVICE_FILTER environment variable is set to LEVEL_ZERO:GPU.
To see the correct device id, please unset SYCL_DEVICE_FILTER.

[ext_oneapi_level_zero:gpu:0] Intel(R) Level-Zero, Intel(R) UHD Graphics 630 1.3 [1.3.0]

=============================================

----------------------------
atomic test
Selected device: Intel(R) UHD Graphics 630
Measured time for parallel execution with std::chrono::steady_clock = 106.599 ms
device result: 1 , cpu result: 1
device result: 1 , cpu result: 1
device result: 3 , cpu result: 3
device result: 4 , cpu result: 4
device result: 8 , cpu result: 8
device result: 9 , cpu result: 9
Atomics test completed, returned OK

----------------------

----------------Test pass-----------------

**Review by tomflinda — APPROVED** [review]
LGTM

**Review by ShengchenJ — APPROVED** [review]
LGTM

**Pull request merged**
